@startuml 演習6-3_ステートマシン図_診察予約システム  
[*] -right-> メニュー画面
メニュー画面 -right-> [*]
メニュー画面 --> 予約確認画面 : 予約
あなたの順番画面 --> メニュー画面
予約確認画面 -right-> あなたの順番画面 : 登録
予約確認画面 -right-> あなたの順番画面 : 確認
予約確認画面 --> メニュー画面 : 取消
メニュー画面 -right-> 今の順番画面 : 診察開始
今の順番画面 -left-> メニュー画面 : 診察終了

@enduml

