@startuml アクティビティ図の例
|顧客|
start
:案内を依頼する;
|給仕|
:テーブルに案内する;
|顧客|
:メニューを渡す;
:メニュー]
:注文を決める;
:注文]
|給仕|
:注文を受ける;
:注文]
fork
:伝票を書く;
:伝票]
forkagain
|料理人|
:料理人に注文を伝える;
:注文]
end fork
|料理人|
:料理を作る;
:料理]
|給仕|
:料理を運ぶ;
:料理]
|顧客|
:伝票を渡す;
:伝票]
:料理を食べる;
:料理]
|給仕|
:代金を払う;
stop
@enduml