@startuml 演習3-4_オブジェクト図
' left to right direction
object "<u>車</u>" as car {
タイヤ=4
}
object "<u>タイヤ1</u>" as taire1 {
サイズ
}
object "<u>タイヤ2</u>" as taire2 {
サイズ
}
object "<u>タイヤ3</u>" as taire3 {
サイズ
}
car  -- taire1
taire1 -- taire2
taire2 -- taire3

@enduml